### ISSUE TITLE
how to display 3d Slice Data

### ISSUE THREAD

**Issue by timesir** [jwbuurlage/slicevis#16]
I have a 3-dimensional numpy array that stores the 3d graphics (slice) to be displayed internally, which can be seen as the data after reconstruction. How can I transfer this 3d array directly to recast3d for direct display of the graphics without first sending it to slice_recon for reconstruction?

**Comment by wjp** [comment]
To do this, you would have to write a custom server that takes the place of slicerecon. It could be a small python script that would listen to slice requests from recast3d, and reply with the requested slices. The script examples/reconstruction_server.py gives a starting point for this. You can replace the callback function in that script by a function that takes slices from your 3d array.
